<?php
$lang = array(
	//general
	'index'					=>	'Index',
	'forum'					=>	'Forum',
	'forums'				=>	'Forums',
	'Error'					=>	'Error',
	'username'				=>	'Username',
	'ipaddr'				=>	'IP Address',
	'message'				=>	'Message',
	'actions'				=>	'Actions',
	'delete'				=>	'Delete',
	'edit'					=>	'Edit',
	'submit'				=>	'Submit',
	'preview'				=>	'Preview',
	'update'				=>	'Update',
	'add'					=>	'Add',
	'upload'				=>	'Upload',
	'export'				=>	'Export',
	'download'				=>	'Download',
	'information'			=>	'Information',
	'category'				=>	'Category',
	'description'			=>	'Description',
	'name'					=>	'Name',
	'posts'					=>	'Posts',
	'topic'					=>	'Topic',
	'topics'				=>	'Topics',
	'post'					=>	'Post',
	'time'					=>	'Time',
	'user'					=>	'User',
	'go'					=>	'Go',
	'on'					=>	'On',
	'posted'				=>	'Posted',
	'by'					=>	'by',
	'enable?'				=>	'Enable?',
	'days'					=>	'Days',
	'save'					=>	'Save changes',
	'and'					=>	'and',
	'or'					=>	'or',
	'rules'					=>	'Rules',
	'registration'			=>	'Registration',
	'minutes'				=>	'Minutes',
	'lastpost'				=>	'Last post',
	'subject'				=>	'Subject',
	'continue'				=>	'Continue',
	'reports'				=>	'Reports',
	'editposts'				=>	'Edit posts',
	'deleteposts'			=>	'Delete posts',
	'cancel'				=>	'Cancel',
	'avatars'				=>	'Avatars',
	'unavailable'			=>	'Unavailable',
	'yes'					=>	'Yes',
	'no'					=>	'No',
	'none'					=>	'None',
	'toc'					=>	'Table of contents',
	
	//index
	'markallread'			=>	'Mark all topics as read',
	'noforums'				=>	'No forums!',
	
	//login
	'notactivated'			=>	'Your account has not been activated yet. Please check the email address you registered with to get the activation code.',
	'badactivation'			=>	'The activation code you entered does not match the one linked with your account.',
	'badlogin'				=>	'Invalid username or password. Click the back button to try again.',
	'emailnotfound'			=>	'Email address was not found.',
	'recoveremailsent'		=>	'An email has been sent to the address you specified with instructions on how to recover the account.',
	'recoveremailcontent'	=>	'It appears you have requested to have your password reset. If this is the case, please go to',
	'forgotpwd'				=>	'Forgot password?',
	'emailaddr'				=>	'Email address:',
	'passnomatch'			=>	'Passwords do not match',
	'passresetsuccess'		=>	'Password successfully reset!',
	'resetpass'				=>	'Reset password',
	'password'				=>	'Password',
	'confirmpwd'			=>	'Confirm password',
	'activationcode'		=>	'Activation code',
	'rememberme'			=>	'Remember me',
	'activateacct'			=>	'Activate your account',
	'language'				=>	'Language',
	'timezone'				=>	'Time zone',
	'badmaintlogin'			=>	'This site is in maintenance mode and only administrators can log in.',
	
	//profile
	'basics'				=>	'Basics',
	'security'				=>	'Account security',
	'avatar'				=>	'User avatar',
	'postsig'				=>	'Post signature',
	'userdeleted'			=>	'This account has been deleted.',
	'profiledesc'			=>	'Welcome to your profile! Here you can manage account settings such as your password or signature, as well as keep an eye on your user\'s stats.',
	'userdetails'			=>	'User details',
	'changepass'			=>	'Change password',
	'newpass'				=>	'New password',
	'currentavatar'			=>	'Current avatar:',
	'noavatar'				=>	'No avatar currently stored.',
	'newavatar'				=>	'Upload new avatar',
	'sigtoolong'			=>	'Your signature may only be $1 characters long, and the one you submitted was $2 characters long',
	'toomanysiglines'		=>	'Your signature may contain $1 lines, and the one you submitted contains $2 lines',
	'changesig'				=>	'Change signature',
	'currentsig'			=>	'Current signature',
	'newsig'				=>	'New signature',
	'changegroup'			=>	'Change user group',
	'revokeprivs'			=>	'Revoke privileges',
	'restoreuser'			=>	'Restore user',
	'deletewarning'			=>	'Are you sure you want to delete this user? This action is reversible.',
	'deleteuser'			=>	'Delete user',
	'withdrawreport'		=>	'Withdraw report',
	'somebodyelse'			=>	'Nothing to see here. This is somebody else\'s profile!',
	'sendPM'				=>	'Send the user a private message',
	'sendas_admin'			=>	'Send as admin-issued warning',
	'send'				=>	'Send',
	'blockPM'				=>	'Disable private messaging',
	'blocknotifs'			=>	'Disable notifications',
	'emailaddrnocolon'		=>	'Email address',
	'badavatarfiletype'		=>	'Invalid file type for your avatar. Only image formats GIF, JPG/JPEG, and PNG are allowed.',
	'uploadfailed'			=>	'File upload failed. Please hit the back button and try again.',
	'filetoobig'			=>	'The file you uploaded is too big. The maximumum allowed filesize is $1 KiB. Please hit the back button and try again.',
	'imagetoobig'			=>	'The image you uploaded is too big. The maximum allowed dimensions are $1x$2 pixels. Please hit the back button and try again.',
	'toobigphpini'			=>	'Your file is larger than the allowed size on the server ($1 KiB). Please hit the back button and try again.',
	'partialupload'			=>	'The file was only partially uploaded. Please hit the back button and try again.',
	'notmpdir'				=>	'A temp directory for uploaded files was not defined on the server. Please contact the server administrator.',
	'avataruploaddesc'		=>	'Upload a new avatar. The maximum allowed file size is $1 KiB and the maximum allowed image size is $2x$3 pixels.',
	'deleteavatar'			=>	'Delete avatar',
	'maxchars'				=>	'Maximum characters: $1',
	'maxlines'				=>	'Maximum lines: $1',
	'heightwarning'			=>	'Maximum height: $1 pixels (if it is taller, it will be cut off)',
	'rsstoken'				=>	'RSS Token (used for viewing user-specific RSS feeds)<br />If you change it, a new random one will be given.',
	'warnings'				=>	'Warnings',
	'sentby'				=>	'Sent by',
	'sentto'				=>	'Sent to',
	'dstprofile'			=>	'Daylight Saving Time (advance one hour)',
	
	//forum viewer
	'pages'					=>	'Pages: ',
	'author'				=>	'Author',
	'replies'				=>	'Replies',
	'topicmoved'			=>	'(Topic moved)',
	'notopics'				=>	'There are no topics in this forum.',
	'rssfeed'				=>	'RSS Feed',
	'prev'					=>	'Prev',
	'next'					=>	'Next',
	'newposts'				=>	'New posts',
	
	//topic viewer
	'edited'				=>	'Edited',
	'lastedited'			=>	'Last edited by $1 on $2',
	'movetopic'				=>	'Move topic',
	'movetoforum'			=>	'Move to forum:',
	'move'					=>	'Move',
	'leaveredirect'			=>	'Leave redirect?',
	'online'				=>	'Online',
	'offline'				=>	'Offline',
	'posts:'				=>	'Posts: ',
	'report'				=>	'Report',
	'quote'					=>	'Quote',
	'postreply'				=>	'Post reply',
	'closednoreply'			=>	'Topic is closed. You may not post a reply.',
	'closetopic'			=>	'Close topic',
	'opentopic'				=>	'Open topic',
	'sticktopic'			=>	'Stick topic',
	'unsticktopic'			=>	'Unstick topic',
	'embed'					=>	'Embed topic',
	'undelete'				=>	'Undelete',
	
	//user list
	'usergroup'				=>	'User group',
	'sortby'				=>	'Sort by',
	'numposts'				=>	'Number of posts',
	'dateregistered'		=>	'Date registered',
	'ascending'				=>	'Ascending',
	'descending'			=>	'Descending',
	'title'					=>	'Title',
	'registered'			=>	'Registered',
	
	//online list
	'usersonline'			=>	'Users online',
	'nobody'				=>	'Nobody',
	'seeall'				=>	'See all',
	
	//search
	'searchresults'		=>	'Search results',
	'noresults'			=>	'Sorry, your search returned no results.',
	'keywords'			=>	'Keywords',
	'show'				=>	'Show',
	'search-undeleted'		=>	'Posts that have not been deleted',
	'search-deleted'		=>	'Posts that have been deleted',
	'allforums'			=>	'All forums',
	
	//banned
	'banned'				=>	'Banned',
	'bannedmsg1'			=>	'You have been banned from this forum',
	'until'				=>	'until',
	'bannedmsg2'			=>	'The moderator or administrator that banned you left you with the following message:',
	'bannedmsg3'			=>	'To contact the board administrator, you may send an email to <a href="mailto:$1">$1</a>.',
	'accessdenied'			=>	'Access denied',
	'noguests'				=>	'You must log in to view this forum.',
	'nogroupview'			=>	'You do not have permission to view these forums.',
	
	//maintenance page
	'maintintro'			=>	'This forum is down for maintenance. The forum administrator said this:',
	'maintintro2'			=>	'If you are an administrator and need to log in, you may do so <a href="' . $base_config['baseurl'] . '/login">here</a>.',
	
	//header
	'profile'				=>	'Profile',
	'userlist'			=>	'User list',
	'register'			=>	'Register',
	'search'				=>	'Search',
	'administration'		=>	'Administration',
	'logout'				=>	'Log out',
	'login'				=>	'Log in',
	
	//general template stuff
	'poweredby'				=>	'Powered by <a href="http://futuresight.org/products/futurebb">FutureBB</a>',
	
	//errors
	'403title'				=>	'403 Forbidden',
	'403head'				=>	'Ouch...',
	'403body1'				=>	'The page "$1" is restricted and you&apos;re not allowed to see it.',
	'403body2'				=>	'Sorry about that. Why don&apos;t you try <a href="javascript:history.go(-1);">going back to where you were</a>?',
	'404title'				=>	'404 Not found',
	'404head'				=>	'Oops...',
	'404body1'				=>	'The path "$1" was not found on this forum!',
	'genericerror'			=>	'<h2>Sorry!</h2><p>The error $1 occurred on the forums. You might want to tell someone in charge if you&apos;ve never seen this before.</p>',
	'invalidxml'			=>	'The file you submitted was not valid XML.',
	'tryagain'				=>	'Try again',
	
	//bbcode errors
	'nolinks'				=>	'You are not allowed to post links.',
	'noimgs'				=>	'You are not allowed to post images.',
	'bracketparam'			=>	'You can&apos;t put brackets in parameters, as you did in a <b>[$1]</b> tag',
	'closenoopen'			=>	'<b>[/$1]</b> found without opening <b>[$1]</b>',
	'expectedfound'		=>	'Invalid tag structure - expected [/$1] and found [/$2]',
	'tagsnotclosed'			=>	'The following tags were not closed: $1',
	'blanksubject'			=>	'Blank subject',
	'blankmsg'				=>	'Blank content',
	'flood_wait' 			=>	'You must wait $1 seconds between posts. Please wait $2  seconds and try again.',
	'flood_hour'			=>	'You may only post $1  posts in one hour. Please wait $2 seconds and try again.',
	'imgwhitelisterror'		=>	'The image URL $1 is not allowed on this forum. You are only allowed to use images hosted on the following domains: $2.',
	'imgblacklisterror'		=>	'The image URL $1 is not allowed on this forum. You are not allowed to use images hosted on the following domains: $2.',
	'toomanynestedquotes'	=>	'The [quote] tag is nested too many times. It can only be nested up to $1 times.',
	
	//posting
	'errordesc'				=>	'The following errors need to be fixed before continuing:',
	'disablesmilies'		=>	'Disable smilies',
	'postreply'				=>	'Post reply',
	'posttopic'				=>	'Post new topic',
	'msgtoolong'			=>	'Your post is more than $1 characters.',
	'topicisclosed'			=>	'This topic is closed',
	'smilies'				=>	'Smilies',
	'imgtag'				=>	'[img] tag',
	'urltag'				=>	'[url] tag',
	'on'					=>	'On',
	'off'					=>	'Off',
	
	//delete post
	'deletepost'			=>	'Delete post',
	'deletepostwarning'		=>	'Are you sure you want to delete this post? If you delete it, you will not be able to recover it. Below is the message you are deleting:',
	'deletetopicwarning'	=>	'If you delete this post, the whole topic will be permanently deleted.',
	
	//edit post
	'editpost'				=>	'Edit post',
	'silentedit'			=>	'Silent edit (don&apos;t update &quot;last edited&quot; data)',
	'signature'				=>	'Signature',
	'signatures'			=>	'Signatures',

	//ip tracker
	'searchip'				=>	'Search IP:',
	'recentactivity'		=>	'Recent activity',
	'userregs'				=>	'User registrations',
	
	//reports
	'unreadreports'			=>	'Unread reports',
	'furtherreview'			=>	'Marked for further review by <b>$1</b>',
	'reason'				=>	'Reason',
	'donotresp'				=>	'Do not respond',
	'accept'				=>	'Accept',
	'reject'				=>	'Reject',
	'markreview'			=>	'Mark for review',
	'nonewreports'			=>	'Yay! There are no new reports!',
	'processedreports'		=>	'Processed reports',
	'reportedby'			=>	'Reported by <b>$1</b> on $2',
	'markedreadby'			=>	'Marked as read by <b>$1</b> on $2',
	'status'				=>	'Status',
	'pending'				=>	'Pending',
	'underreview'			=>	'Under review',
	'rejected'				=>	'Rejected',
	'accepted'				=>	'Accepted',
	'noresp'				=>	'No response',
	'withdrawnbyreporter'	=>	'Withdrawn by reporter',
	'unknown'				=>	'Unknown',
	'nooldreports'			=>	'Yay! There are no old reports!',
	'reportpost'			=>	'Report post',
	'reportpostreason'		=>	'Please enter a short reason why you are reporting this post.',
	'systemreportmsg'		=>	'This report was automatically generated by FutureBB.',

	//trash bin
	'trashbindesc'			=>	'Deleted topics and posts can be recovered here.',
	'deletedbyon'			=>	'$1 deleted by <b>$2</b> on $3',
	'recentdeleted'			=>	'Recently deleted $1',
	'deletiontime'			=>	'Deletion time',
	'deletedby'				=>	'Deleted by',

	//styles
	'styleconflict'			=>	'A style set with this name already exists. Please rename your stylesheet and retry.',
	'invalidfile'			=>	'Invalid file.',
	'appearanceandstyle'	=>	'Appearance and style',
	'stylesets'				=>	'Style sets',
	'styleset'				=>	'Style set',
	'installnewcss'			=>	'Install new style set',
	'cssfile'				=>	'CSS File:',
	'logo'					=>	'Logo',
	'pngfile'				=>	'PNG File:',
	'favicon'				=>	'Favicon',
	'icofile'				=>	'ICO File:',
	'nofileuploads'			=>	'Your server does not accept file uploads. Please change the "allow_file_uploads" setting in your php.ini if possible.',
	'install'				=>	'Install',
	'replace'				=>	'Replace',
	'icon'					=>	'Icon',
	
	//notifications
	'newreports'			=>	'There are new reports',
	'maintenabled'			=>	'Maintenance mode is enabled',
	'maintsched'			=>	'This forum will automatically go into maintenance mode at $1. At that time, all non-admin users will lose access.',
	'unreadnotifications'	=>	'You have $1 unread notifications',
	'messages'				=>	'Messages',
	'user_sent_warning'		=>	'The admin or moderator $1 issued the following message to you.',
	'user_sent_msg'			=>	'The user $1 sent the following message to you.',
	'user_mentioned_you'	=>	'The user $1 mentioned you in a post in the topic ',
	'report_abuse'			=>	'Report abuse',
	'send_appeal'			=>	'Send appeal',
	'sent'					=>	'Sent',
	'couldnot_display_notif'=>	'The notification could not be displayed because the type of message could not be determined.',
	'nonotifs'				=>	'You have no notifications at the moment',
	'maintenance'			=>	'Maintenance',
	
	//bbcode
	'wrote'					=> 'wrote',
	'bbcode'				=> 'BBCode',
	
	//bbcode help page
	'produces'				=> 'produces',
	'bbcodehelp'			=> 'BBCode Help',
	'bbcodehelpintro'		=> 'BBCode is a tool that lets you format your posts',
	'basicformatting'		=> 'Basic formatting',
	'tagssupported'			=> 'The following tags are supported:',
	'boldtext'				=> 'Bold text',
	'italictext'			=> 'Italic text',
	'underlinedtext'		=> 'Underlined text',
	'struckouttext'			=> 'Struckouttext',
	'bluetext'				=> 'Blue text',
	'magentatext'			=> 'Magenta',
	'quotes'				=> 'Quotes',
	'textquoting'			=> 'This is the text I am quoting.',
	'johnsmith'				=> 'John Smith', //replace with whatever generic name you want
	'linksandimages'		=> 'Links and images',
	
	//IMPORTANT: DO NOT REMOVE OR MODIFY THIS COMMENT OR EXTENSIONS WILL NOT WORK
	//extensions
);