<?php
$lang = array(
	//general
	'index'				=>	'Index',
	'forum'				=>	'Forum',
	'forums'				=>	'Forums',
	'Error'				=>	'Error',
	'username'			=>	'Username',
	'ipaddr'				=>	'IP Address',
	'message'				=>	'Message',
	'actions'				=>	'Actions',
	'delete'				=>	'Delete',
	'edit'				=>	'Edit',
	'submit'				=>	'Submit',
	'preview'				=>	'Preview',
	'update'				=>	'Update',
	'add'				=>	'Add',
	'upload'				=>	'Upload',
	'export'				=>	'Export',
	'download'			=>	'Download',
	'information'			=>	'Information',
	'category'			=>	'Category',
	'description'			=>	'Description',
	'name'				=>	'Name',
	'posts'				=>	'Posts',
	'topic'				=>	'Topic',
	'topics'				=>	'Topics',
	'post'				=>	'Post',
	'time'				=>	'Time',
	'user'				=>	'User',
	'go'					=>	'Go',
	'on'					=>	'On',
	'posted'				=>	'Posted',
	'by'					=>	'by',
	'enable?'				=>	'Enable?',
	'days'				=>	'Days',
	'save'				=>	'Save changes',
	'and'				=>	'and',
	'or'					=>	'or',
	'rules'				=>	'Rules',
	'registration'			=>	'Registration',
	'minutes'				=>	'Minutes',
	'lastpost'			=>	'Last post',
	'subject'				=>	'Subject',
	'continue'			=>	'Continue',
	
	//index
	'markallread'			=>	'Mark all topics as read',
	'noforums'			=>	'No forums!',
	
	//login
	'notactivated'			=>	'Your account has not been activated yet. Please check the email address you registered with to get the activation code.',
	'badactivation'		=>	'The activation code you entered does not match the one linked with your account.',
	'badlogin'			=>	'Invalid username or password. Click the back button to try again.',
	'emailnotfound'		=>	'Email address was not found.',
	'recoveremailsent'		=>	'An email has been sent to the address you specified with instructions on how to recover the account.',
	'recoveremailcontent'	=>	'It appears you have requested to have your password reset. If this is the case, please go to',
	'forgotpwd'			=>	'Forgot password?',
	'emailaddr'			=>	'Email address:',
	'passnomatch'			=>	'Passwords do not match',
	'passresetsuccess'		=>	'Password successfully reset!',
	'resetpass'			=>	'Reset password',
	'password'			=>	'Password',
	'confirmpwd'			=>	'Confirm password',
	'activationcode'		=>	'Activation code',
	'rememberme'			=>	'Remember me',
	'activateacct'			=>	'Activate your account',
	'language'			=>	'Language',
	'timezone'			=>	'Time zone',
	
	//registration
	'bademail'			=>	'Invalid email address',
	'duplicateuser'		=>	'Username already exists',
	'badusername'			=>	'Username must only contain letters, numbers, periods, hyphens, and underscores. Invalid character: $1',
	'dupeipreg'			=>	'A user from your IP address has already registered within the past two hours. Please come back later and try again.',
	'verifyemail'			=>	'Someone has registered using your email address as the user $1. If this is you, go to the login page ($2/login?activate) and log in, and when it asks you for an access code, please use the following:
$3
If this is not you, then please disregard this message.',
	'emailaddrnocolon'		=>	'Email address',
	'botchallenge'			=>	'You failed the anti-bot challenge',
	'shortusername'		=>	'Your username must be longer than 4 characters',
	
	//profile
	'basics'				=>	'Basics',
	'security'			=>	'Account security',
	'avatar'				=>	'User avatar',
	'postsig'				=>	'Post signature',
	'userdeleted'			=>	'This account has been deleted.',
	'profiledesc'			=>	'Welcome to your profile! Here you can manage account settings such as your password or signature, as well as keep an eye on your user\'s stats.',
	'userdetails'			=>	'User details',
	'changepass'			=>	'Change password',
	'newpass'				=>	'New password',
	'currentavatar'		=>	'Current avatar:',
	'noavatar'			=>	'No avatar currently stored.',
	'newavatar'			=>	'Upload new avatar',
	'sigtoolong'			=>	'Your signature may only be $1 characters long, and the one you submitted was $2 characters long',
	'toomanysiglines'		=>	'Your signature may contain $1 lines, and the one you submitted contains $2 lines',
	'changesig'			=>	'Change signature',
	'currentsig'			=>	'Current signature',
	'newsig'				=>	'New signature',
	'changegroup'			=>	'Change user group',
	'revokeprivs'			=>	'Revoke privileges',
	'restoreuser'			=>	'Restore user',
	'deletewarning'		=>	'Are you sure you want to delete this user? This action is reversible.',
	'deleteuser'			=>	'Delete user',
	'withdrawreport'		=>	'Withdraw report',
	'somebodyelse'			=>	'Nothing to see here. This is somebody else\'s profile!',
	'sendPM'				=>	'Send the user a private message',
	'sendas_admin'			=>	'Send as admin-issued warning',
	'send'				=>	'Send',
	'blockPM'				=>	'Disable private messaging',
	'blocknotifs'			=>	'Disable notifications',
	
	//forum viewer
	'pages'					=>	'Pages: ',
	'author'				=>	'Author',
	'replies'				=>	'Replies',
	'topicmoved'			=>	'(Topic moved)',
	'notopics'				=>	'There are no topics in this forum.',
	
	//topic viewer
	'edited'				=>	'Edited',
	'lastedited'			=>	'Last edited by $1 on $2',
	'movetopic'				=>	'Move topic',
	'movetoforum'			=>	'Move to forum:',
	'move'					=>	'Move',
	'leaveredirect'			=>	'Leave redirect?',
	'online'				=>	'Online',
	'offline'				=>	'Offline',
	'posts:'				=>	'Posts:',
	'report'				=>	'Report',
	'quote'					=>	'Quote',
	'postreply'				=>	'Post reply',
	'closednoreply'			=>	'Topic is closed. You may not post a reply.',
	'closetopic'			=>	'Close topic',
	'opentopic'				=>	'Open topic',
	'sticktopic'			=>	'Stick topic',
	'unsticktopic'			=>	'Unstick topic',
	
	//user list
	'usergroup'				=>	'User group',
	'sortby'				=>	'Sort by',
	'numposts'				=>	'Number of posts',
	'dateregistered'		=>	'Date registered',
	'ascending'				=>	'Ascending',
	'descending'			=>	'Descending',
	'title'					=>	'Title',
	'registered'			=>	'Registered',
	
	//online list
	'usersonline'			=>	'Users online',
	'nobody'				=>	'Nobody',
	'seeall'				=>	'See all',
	
	//search
	'searchresults'		=>	'Search results',
	'noresults'			=>	'Sorry, your search returned no results.',
	'keywords'			=>	'Keywords',
	'show'				=>	'Show',
	'search-undeleted'		=>	'Posts that have not been deleted',
	'search-deleted'		=>	'Posts that have been deleted',
	'allforums'			=>	'All forums',
	
	//banned
	'banned'				=>	'Banned',
	'bannedmsg1'			=>	'You have been banned from this forum',
	'until'				=>	'until',
	'bannedmsg2'			=>	'The moderator or administrator that banned you left you with the following message:',
	'bannedmsg3'			=>	'To contact the board administrator, you may send an email to <a href="mailto:$1">$1</a>.',
	
	//maintenance page
	'maintintro'			=>	'This forum is down for maintenance. The forum administrator said this:',
	
	//header
	'profile'				=>	'Profile',
	'userlist'			=>	'User list',
	'register'			=>	'Register',
	'search'				=>	'Search',
	'administration'		=>	'Administration',
	'logout'				=>	'Log out',
	'login'				=>	'Log in',
	
	//general template stuff
	'poweredby'				=>	'Powered by <a href="http://futuresight.org/products/futurebb">FutureBB</a>',
	
	//errors
	'403title'				=>	'403 Forbidden',
	'403head'				=>	'Ouch...',
	'403body1'				=>	'The page "$1" is restricted and you&apos;re not allowed to see it.',
	'403body2'				=>	'Sorry about that. Why don&apos;t you try <a href="javascript:history.go(-1);">going back to where you were</a>?',
	'404title'				=>	'404 Not found',
	'404head'				=>	'Oops...',
	'404body1'				=>	'The path "$1" was not found on this forum!',
	'genericerror'			=>	'<h2>Sorry!</h2><p>The error $1 occurred on the forums. You might want to tell someone in charge if you&apos;ve never seen this before.</p>',
	'invalidxml'			=>	'The file you submitted was not valid XML.',
	'tryagain'				=>	'Try again',
	
	//bbcode errors
	'nolinks'				=>	'You are not allowed to post links.',
	'noimgs'				=>	'You are not allowed to post images.',
	'bracketparam'			=>	'You can&apos;t put brackets in parameters, as you did in a <b>[$1]</b> tag',
	'closenoopen'			=>	'<b>[/$1]</b> found without opening <b>[$1]</b>',
	'expectedfound'		=>	'Invalid tag structure - expected [/$1] and found [/$2]',
	'tagsnotclosed'		=>	'The following tags were not closed: $1',
	'blanksubject'			=>	'Blank subject',
	'blankmsg'			=>	'Blank content',
	'flood_wait' 			=>	'You must wait $1 seconds between posts. Please wait $2  seconds and try again.',
	'flood_hour'			=>	'You may only post $1  posts in one hour. Please wait $2 seconds and try again.',
	'imgwhitelisterror'		=>	'The image URL $1 is not allowed on this forum. You are only allowed to use images hosted on the following domains: $2.',
	'imgblacklisterror'		=>	'The image URL $1 is not allowed on this forum. You are not allowed to use images hosted on the following domains: $2.',
	
	//posting
	'errordesc'			=>	'The following errors need to be fixed before continuing:',
	'disablesmilies'		=>	'Disable smilies',
	'postreply'			=>	'Post reply',
	'posttopic'			=>	'Post new topic',
	'msgtoolong'			=>	'Your post is more than $1 characters.',
	'topicisclosed'		=>	'This topic is closed',
	
	//delete post
	'deletepost'			=>	'Delete post',
	'deletepostwarning'		=>	'Are you sure you want to delete this post? If you delete it, you will not be able to recover it. Below is the message you are deleting:',
	
	//edit post
	'editpost'			=>	'Edit post',
	'silentedit'			=>	'Silent edit (don&apos;t update &quot;last edited&quot; data)',
	
	//admin pages
	'bans'					=>	'Bans',
	'trashbin'				=>	'Trash bin',
	'reports'				=>	'Reports',
	'censoring'				=>	'Censoring',
	'iptracker'				=>	'IP Tracker',
	'usergroups'			=>	'User groups',
	'maintenance'			=>	'Maintenance',
	'style'					=>	'Style',
	'extensions'			=>	'Extensions',
	
	//bans
	'newban'				=>	'Add new ban',
	'editban'				=>	'Edit ban',
	'deleteban'				=>	'Delete ban',
	'expires'				=>	'Expires',
	'never'					=>	'Never',
	'deletebanconfirm'		=>	'Are you sure you want to delete this ban?',
	'jk'					=>	'Just kidding',
	'signature'				=>	'Signature',
	'signatures'			=>	'Signatures',
	
	//censoring
	'censorintro'			=>	'You may use this page to set inappropriate words to censor.<br />This will not affect old posts unless the reparse posts function is used (available on the <a href="' . $base_config['baseurl'] . '/admin/maintenance">maintenance page</a>).',
	'newword'				=>	'Add new word',
	'find'					=>	'Find',
	'replacewith'			=>	'Replace with',
	'importcensor1'			=>	'Import dictionary',
	'importcensor2'			=>	'If you want, you can import a pre-defined dictionary of censored words.',
	'exportcensor'			=>	'To export the censoring list so it can be used on another forum, please click the download link below.',
	'imghostrestriction'	=>	'Image host restrictions',
	'hostlist'				=>	'Domain names that are allowed/disallowed (set blacklist/whitelist mode above, and put one domain per line)',
	'whitelist'				=>	'Whitelist',
	'blacklist'				=>	'Blacklist',
	'none'					=>	'None',
	
	//admin forums
	'forumname'				=>	'Forum name',
	'permissions'			=>	'Permissions',
	'grouptitle'			=>	'Group title',
	'viewforum'				=>	'View forum',
	'posttopics'			=>	'Post topics',
	'postreplies'			=>	'Post replies',
	'editcats'				=>	'Edit categories',
	'catname'				=>	'Category name',
	'sortpos'				=>	'Sort position',
	'delete?'				=>	'Delete?',
	'updatecats'			=>	'Update categories',
	'editforums'			=>	'Edit forums',
	'newforum'				=>	'Add new forum',
	'newforumname'			=>	'New forum',
	'forumname'				=>	'Forum name',
	'updateforums'			=>	'Update forums',

	//ip tracker
	'searchip'				=>	'Search IP:',
	'recentactivity'		=>	'Recent activity',
	'userregs'				=>	'User registrations',
	
	//maintenance (admin page)
	'redirmsg'				=>	'If you are not redirected within a few seconds, <a href="$1">click here</a> to continue.',
	'updatingtopic'			=>	'Updating topic #$1',
	'updatingforum'			=>	'Updating forum #$1',
	'reparsingposts'		=>	'Reparsing posts - now is a good time to get off the computer for a little while. :)',
	'reparsingpost'			=>	'Reparsing post #$1',
	'reparsingsigs'			=>	'Reparsing signatures - now is a good time to get off the computer for a little while. :)',
	'reparsingsig'			=>	'Reparsing signature #$1',
	'rebuildingsearch'		=>	'Rebuilding search index - now is a good time to get off the computer for a little while. :)',
	'procpost'				=>	'Processing post #$1',
	'updatingpostcounts'	=>	'Updating user post counts - now is a good time to get off the computer for a little while. :)',
	'recountinguser'		=>	'Recounting user #$1',
	'recountingtopicreplies'=>	'Recalculating topic reply counts - now is a good time to get off the computer for a little while. :)',
	'maintenancedesc'		=>	'From this page, you can run the various maintenance utilities necessary to help keep your forum working.',
	'rebuildsearch'			=>	'Rebuild search index',
	'rebuildsearchdesc'		=>	'If there are problems searching, you can rebuild the search index.',
	'deleteorphans'			=>	'Delete orphaned topics',
	'deleteorphansdesc'		=>	'If you are ever getting a message saying a topic has no posts in it, run this utility to remove all of them.',
	'updatelastpost'		=>	'Update topic/forum last post data',
	'updatelastpostdesc'	=>	'If the last post data in topics and forums appears to be invalid, run this tool to fix it.',
	'reparse'				=>	'Reparse',
	'reparsedesc'			=>	'This forum pre-parses BBCode, meaning that the BBCode is converted into HTML at the time of posting/editing the post. This means that any changes to BBCode will not affect old posts. If you have added new BBCode and want to apply it on old posts, you should run this utility.',
	'reparseposts'			=>	'Reparse all posts',
	'reparsesigs'			=>	'Reparse all signatures',
	'updatecounts'			=>	'Update counts',
	'updateuserpostcounts'	=>	'Update user post counts',
	'updateforumpostcounts'	=>	'Update forum post counts',
	'updateforumtopiccounts'=>	'Update forum topic counts',
	'updatetopicpostcounts'	=>	'Update topic post counts',
	
	//reports
	'unreadreports'			=>	'Unread reports',
	'furtherreview'			=>	'Marked for further review by <b>$1</b>',
	'reason'				=>	'Reason',
	'donotresp'				=>	'Do not respond',
	'accept'				=>	'Accept',
	'reject'				=>	'Reject',
	'markreview'			=>	'Mark for review',
	'nonewreports'			=>	'Yay! There are no new reports!',
	'processedreports'		=>	'Processed reports',
	'reportedby'			=>	'Reported by <b>$1</b> on $2',
	'markedreadby'			=>	'Marked as read by <b>$1</b> on $2',
	'status'				=>	'Status',
	'pending'				=>	'Pending',
	'underreview'			=>	'Under review',
	'rejected'				=>	'Rejected',
	'accepted'				=>	'Accepted',
	'noresp'				=>	'No response',
	'withdrawnbyreporter'	=>	'Withdrawn by reporter',
	'unknown'				=>	'Unknown',
	'nooldreports'			=>	'Yay! There are no old reports!',
	'reportpost'			=>	'Report post',
	'reportpostreason'		=>	'Please enter a short reason why you are reporting this post.',
	'systemreportmsg'		=>	'This report was automatically generated by FutureBB.',

	//trash bin
	'trashbindesc'			=>	'Deleted topics and posts can be recovered here.',
	'deletedbyon'			=>	'$1 deleted by <b>$2</b> on $3',
	'recentdeleted'			=>	'Recently deleted $1',
	'deletiontime'			=>	'Deletion time',
	'deletedby'				=>	'Deleted by',
	
	//user groups
	'defaultusergroup'		=>	'Default user group:',
	'newusergroup'			=>	'Create new user group',
	'groupname'				=>	'Group name',
	'groupnamedesc'			=>	'This is the title of the group itself.',
	'usertitle'				=>	'User title',
	'usertitledesc'			=>	'This will show up under a user&apos;s username in their posts.',
	'editposts'				=>	'Edit posts',
	'editpostsdesc'			=>	'This option allows users to edit their own posts.',
	'deleteposts'			=>	'Delete posts',
	'deletepostsdesc'		=>	'This option allows users to delete their own posts.',
	'modprivs'				=>	'Moderator privileges',
	'modprivsdesc'			=>	'This option gives users access to the moderator tools, which include being able to edit and delete everybody&apos;s posts, ban users, and view deleted posts.',
	'adminprivs'			=>	'Administrator privileges',
	'adminprivsdesc'		=>	'This option gives users access to the complete admin panel.',
	'allowsig'				=>	'Allow signature',
	'allowsigdesc'			=>	'This option allows users to have a signature under their posts.',
	'viewuserlist'			=>	'View user list',
	'viewuserlistdesc'		=>	'This option allows users to view the user list.',
	'postlinks'				=>	'Post links',
	'postlinksdesc'			=>	'This option allows users to include the [url] tag in their posts.',
	'postimgs'				=>	'Post images',
	'postimgsdesc'			=>	'This option allows users to include the [img] tag in their posts.',
	'postflood'				=>	'Post flood',
	'postflooddesc'			=>	'Users must wait this many seconds between posts. Set to zero for no limit.',
	'maxpostsperhour'		=>	'Max posts per hour',
	'maxpostsperhourdesc'	=>	'Users in this group may only post this many posts in one hour, and must wait until fewer than this many posts have been posted by that user in the past hour before continuing. Set to zero for no limit.',
	'userlistvisgrps'		=>	'Visible groups on user list',
	'userlistvisgrpsdesc'	=>	'If a user in this group visits the user list, only users in the groups checked above will be visible.',
	'promoteto'				=>	'Promote to',
	'dontpromote'			=>	'[Do not promote]',
	'after'					=>	'after',
	'deleteusergroup'		=>	'Delete user group',
	'deletegroupconfirm'	=>	'Are you sure you want to delete the user group &quot;$1&quot;?',
	'moveallusersto'		=>	'Move all users in this group to: ',

	//styles
	'styleconflict'			=>	'A style set with this name already exists. Please rename your stylesheet and retry.',
	'invalidfile'			=>	'Invalid file.',
	'appearanceandstyle'	=>	'Appearance and style',
	'stylesets'				=>	'Style sets',
	'styleset'				=>	'Style set',
	'installnewcss'			=>	'Install new style set',
	'cssfile'				=>	'CSS File:',
	'logo'					=>	'Logo',
	'pngfile'				=>	'PNG File:',
	'favicon'				=>	'Favicon',
	'icofile'				=>	'ICO File:',
	'nofileuploads'			=>	'Your server does not accept file uploads. Please change the "allow_file_uploads" setting in your php.ini if possible.',
	'install'				=>	'Install',
	'replace'				=>	'Replace',
	'icon'					=>	'Icon',

	//extensions
	'uploadfailed'			=>	'File upload failed.',
	'notzip'				=>	'The file you uploaded is not a ZIP file.',
	'noinfophp'				=>	'The extension did not have an info.php file',
	'badextinfo'			=>	'The $ext_info variable was either not set or not an array in the info.php file.',
	'extinfomissingkey'		=>	'The $ext_info variable was missing the following required key: <b>$1</b>',
	'extinstallation'		=>	'Extension installation',
	'makingdbchanges'		=>	'Making database changes - success',
	'runninginstallphp'		=>	'Running install.php - success',
	'copyingfiles'			=>	'Copying files - success',
	'nochangesvar'			=>	'The variable $changes was not set in changes.php',
	'changesmissingkey'		=>	'$changes[$1] is missing a key.',
	'invalidchangetype'		=>	'Invalid change type: ',
	'installcomplete'		=>	'Installation complete!',
	'unzipfailed'			=>	'Something went wrong with unzipping. Not sure what. :(',
	'installnewext'			=>	'Install new extension',

	//admin index
	'boardsettings'			=>	'Board settings',
	'boardtitle'			=>	'Board title',
	'adminemail'			=>	'Administrator email',
	'onlinetimeout'			=>	'Online timeout',
	'allowPM'				=>	'Allow private messaging',
	'allownotifs'			=>	'Allow notifications',
	'onlinetimeoutdesc'		=>	'If a user does not visit any page after this many seconds, they will be considered offline. Use 0 to disable online/offline display.',
	'verifyregs'			=>	'Verify new registrations',
	'verifyregsdesc'		=>	'Verify new user registrations by emailing them an access code',
	'general'				=>	'General',
	'userstopicsposts'		=>	'Users, topics, and posts',
	'enableavatars'			=>	'Enable avatars',
	'enableavatarsdesc'		=>	'An avatar is a user icon that will show next to all of their posts.',
	'rulesdesc'				=>	'Users must agree to these rules when they register. This is not parsed as BBCode and may contain HTML.',
	'announcement'			=>	'Announcement',
	'announcementdesc'		=>	'Here you may specify an announcement to appear in the top banner under the navigation bar. You may use HTML as this is not parsed as BBCode.',
	'enableannouncement'	=>	'Enable announcement?',
	'siteappearance'		=>	'Site appearance',
	'customfooter'			=>	'Here you may specify custom text to appear below the &quot;Powered by FutureBB&quot; message.',
	'addl_header_links'		=>	'Additional header links<br />Enter them in the following format: <code>3:&lt;a href=&quothttp://yoursite.com&quot&gt;My website&lt;/a&gt;</code><br />That example would make it appear as the third header link.',
	'topicsperpage'			=>	'Topics per page',
	'postsperpage'			=>	'Posts per page',
	'showpostcounts'		=>	'Show user post counts',
	'showpostcountsdesc'	=>	'Show users&apos; post counts in their posts',
	'zeronolimit'			=>	'Set an option to zero for no limit',
	'maxchars'				=>	'Maximum number of characters',
	'maxlines'				=>	'Maximum number of lines',
	'maxheight'				=>	'Maximum height (pixels)',
	'maintenancemode'		=>	'Maintenance mode',
	'maintenancemsg'		=>	'Maintenance message:',
	'autoactivatemaint'		=>	'Automatically activate maintenance mode in',
	'maintschedpanel'		=>	'(Maintenance mode is already scheduled to turn on at $1).',
	'autodeactivatemaint'	=>	'Automatically deactivate maintenance mode in ',
	'maintoffschedpanel'	=>	'(Maintenance mode is already scheduled to turn off at $1).',
	'serverinfo'			=>	'Server info',
	'fbbversion'			=>	'FutureBB Version',
	'database'				=>	'Database',
	'os'					=>	'Operating system',
	'newversionmsg'			=>	'A new version of FutureBB is available! You can download it on <a href="http://futuresight.org/products/futurebb">the FutureSight Technologies website</a>.',
	
	//notifications
	'newreports'			=>	'There are new reports',
	'maintenabled'			=>	'Maintenance mode is enabled',
	'maintsched'			=>	'This forum will automatically go into maintenance mode at $1. At that time, all non-admin users will lose access.',
	'unreadnotifications'	=>	'You have $1 unread notifications',
	'messages'				=>	'Messages',
	'user_sent_warning'		=>	'The admin or moderator $1 issued the following message to you.',
	'user_sent_msg'			=>	'The user $1 sent the following message to you.',
	'user_mentioned_you'	=>	'The user $1 mentioned you in a post in the topic ',
	'report_abuse'			=>	'Report abuse',
	'send_appeal'			=>	'Send appeal',
	'sent'					=>	'Sent',
	'couldnot_display_notif'=>	'The notification could not be displayed because the type of message could not be determined.',
	'nonotifs'				=>	'You have no notifications at the moment',
	
	//bbcode
	'wrote'					=> 'wrote',
	
	//bbcode help page
	'produces'				=> 'produces',
	'bbcodehelp'			=> 'BBCode Help',
	'bbcodehelpintro'		=> 'BBCode is a tool that lets you format your posts',
	'basicformatting'		=> 'Basic formatting',
	'tagssupported'			=> 'The following tags are supported:',
	'boldtext'				=> 'Bold text',
	'italictext'			=> 'Italic text',
	'underlinedtext'		=> 'Underlined text',
	'struckouttext'			=> 'Struckouttext',
	'bluetext'				=> 'Blue text',
	'magentatext'			=> 'Magenta',
	'quotes'				=> 'Quotes',
	'textquoting'			=> 'This is the text I am quoting.',
	'johnsmith'				=> 'John Smith', //replace with whatever generic name you want
	'linksandimages'		=> 'Links and images',
);